var _insufficient_permission_exception_8java =
[
    [ "de.sickones.cahbackend.errorHandling.InsufficientPermissionException", "classde_1_1sickones_1_1cahbackend_1_1error_handling_1_1_insufficient_permission_exception.html", "classde_1_1sickones_1_1cahbackend_1_1error_handling_1_1_insufficient_permission_exception" ]
];